### ISSUE TITLE
Searching users

### ISSUE THREAD

**Issue by Maryom** [GitHawkApp/GitHawk#1794] opened 2018-05-07 08:46 UTC
Hi,

Thanks for sending me TestFlight.

I’m testing version 1.20

I have a suggestion if you don’t mind. I think it’s better to add searching for users to the search feature.

Thanks.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jdisho** [comment] 2018-05-07 08:50
Hey @Maryom 

This issue is a duplicate of: https://github.com/GitHawkApp/GitHawk/issues/345 😊

**Closed by jdisho** 2018-05-07 08:50 UTC

**Comment by Maryom** [comment] 2018-05-07 09:17
>Hey @Maryom  ...

@jdisho I didn’t notice that 😅

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
