### ISSUE TITLE
Api Status

### ISSUE THREAD

**Issue by SuriAditya** [GitHawkApp/GitHawk#2819] opened 2019-08-19 09:27 UTC
Getting api status error

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPad7,5 (iOS 12.4)
TestFlight: false
</pre>
</details>

**Comment by tripleee** [comment] 2019-09-07 11:32
This is too vague to be sure; but probably a duplicate of #2820

**Comment by BasThomas** [comment] 2019-09-14 07:55
Hi @SuriAditya, thanks for letting us know! This has been fixed and will be available in the next update.

You should be able to use the app regardless of the reported error.

See #2546

**Closed by BasThomas** 2019-09-14 07:55 UTC
Labels: 🧹 duplicate
