### ISSUE TITLE
Emoji displayed incorrectly

### ISSUE THREAD

**Issue by aahung** [GitHawkApp/GitHawk#2652] opened 2019-02-22 11:16 UTC
As you can see below, the second emoji should be different.

![GitHawk Upload by aahung](https://i.imgur.com/SfPQ4i6.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone X (iOS 12.1.4)
TestFlight: false
</pre>
</details>

**Comment by viktorasl** [comment] 2019-02-22 11:38
Dupe of #2605, fixed w/ #2616.

**Closed** 2019-02-22 12:50 UTC
