### ISSUE TITLE
Api for Github Status

### ISSUE THREAD

**Issue by yjqiang** [GitHawkApp/GitHawk#2552] opened 2018-12-17 01:23 UTC
https://status.github.com/messages
"status.github.com has been deprecated. You can find the current github system status at githubstatus.com."
And Githawk is using status.github.com to check the status. So maybe you should switch to githubstatus.com?

**Comment by Sherlouk** [comment] 2018-12-17 01:30
Hey! This looks to be a duplicate of #2546 which has been picked up in PR #2547 which will hopefully make it's way through shortly!

**Closed by Sherlouk** 2018-12-17 01:30 UTC

**Comment by j-f1** [comment] 2018-12-17 01:31
You can also [join the beta](https://testflight.apple.com/join/QIVXLkkn) to get these updates faster.

**Comment by yjqiang** [comment] 2018-12-17 01:40
> Hey! This looks to be a duplicate of #2546 which has been picked up in PR #2547 which will hopefully make it's way through shortly!

I just searched with the keyword "states". Sorry for my bad English.

**Comment by Sherlouk** [comment] 2018-12-17 08:18
No need to apologise 😄Thanks for raising an issue!
