### ISSUE TITLE
Support emojis in label

### ISSUE THREAD

**Issue by viktorasl** [GitHawkApp/GitHawk#2641] opened 2019-02-14 11:00 UTC
Expected to have :bug: emoji displayed

![GitHawk Upload by viktorasl](https://i.imgur.com/gTggVYr.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment] 2019-02-14 11:37
Dupe of #1616

**Closed by Sherlouk** 2019-02-14 11:37 UTC
