### ISSUE TITLE
Closed issue is found when is:open is searched

### ISSUE THREAD

**Issue by 343max** [GitHawkApp/GitHawk#2751] opened 2019-05-10 17:05 UTC
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.28.0 (1554002345)
Device: iPhone X (iOS 12.2)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment] 2019-05-10 22:18
Closing as a duplicate of #2750

**Closed by BasThomas** 2019-05-10 22:18 UTC
