### ISSUE TITLE
Credentials Issue

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2165] opened 2018-09-14 00:15 UTC
**Describe the bug**
I'm trying to fix my PR #2157.

My example gif shows a "something went wrong" error. At first, I assumed it was some maybe network issue or something since the error is the generic one (so who really knows). I just assumed it didn't code I changed since I didn't really change anything that I can see would ever effect it. 

I printed the result in `addCommentClient.swift` under the `case: .faliure` 

the result is: 

> failure(Optional(Although you appear to have the correct authorization credentials,
>the `GitHawkApp` organization has enabled OAuth App access restrictions, meaning that data
>access to third-parties is limited. For more information on these restrictions, including
>how to whitelist this app, visit
>https://help.github.com/articles/restricting-access-to-your-organization-s-data/
>))

I guessed it may have been my Github Client ID or Secret but 

1. The app shouldn't sign me in if those aren't valid (pretty sure)
2. I added them again to make sure it was right and I'm pretty sure they are fine.

Note: Using the Testflight version of githawk works fine.

**To Reproduce**
Umm.. unsure.

**Expected behavior**
For the comment to post successfully 

**Screenshots**
See PR with gif

Anyone have an idea of stuff I can try? Did I just forget to do something obvious? Does my code in the PR seem to mess something up in this regard? (I really don't think its the code cause it works for my other repos
 
Any help is appreciated

**Comment by rnystrom** [comment] 2018-09-14 10:50
So is this a bug with the latest App Store version? Do we need to disable OAuth restrictions?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment] 2018-09-14 12:04
@rnystrom no this post is from the App Store version.
Not sure what is causing the error on my specific branch

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jsg2021** [comment] 2018-09-18 23:28
i’m also getting “something went wrong” on various projects.

**Comment by jsg2021** [comment] 2018-09-20 02:18
I don’t have any. Just what the public has.

**Comment by rnystrom** [comment] 2018-09-22 18:59
I thought I saw some weird inconsistencies w/ auth between PAT and normal login b/c of third-party scopes. Is that what this is from?

**Comment by Huddie** [comment] 2018-09-22 23:52
I logged in normally. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment] 2018-10-17 04:07
@rnystrom since we closed my issue ticket today, do you have any idea what may cause it.

Also expanding on op that I’ve received this error when:
- Posting comments
- Opening/closing tickets

**Comment by rnystrom** [comment] 2018-10-17 14:16
I don’t and haven’t had time to investigate. Would love someone’s help here. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment] 2018-10-17 14:32
@Huddie testflight

The failure to post a comment is this newest one “...7256” and was prosecuted on this repository

And the close reopen auth error was the testflight build right before it “...0019” and was produced in the cr-api-ux repository

Both issues have worked at other times in the same exact repository so it’s not restricted permissions

**Comment by ijm8710** [comment] 2018-10-27 20:06
@Huddie is there any other info I could give to help. I’m seeing this almost daily, but only in this app, works fine in codehub and native GitHub

**Comment by ijm8710** [comment] 2018-10-28 17:36
@rnystrom I’m seeing this super super often, essentially several times daily. I know you said a week and a half ago, you didn’t have a ton of time to investigate yourself. Is there anything that would be helpful to provide for perhaps someone to take over with more detail. Among the people most involved like bas and others, any idea who’s subject matter this best fits with?

Not to overreact, but imo this is a pretty significant big, it essentially makes me resort to going to github or another 3 party app every time just to post a comment which could def drive users away.

**Comment by rnystrom** [comment] 2018-10-28 18:05
@ijm8710 you seem to be the one hitting the the most, so you’d be a great champion to fixing it. Some ways you can contribute:

- Use Flex network debugging to inspect error messages and codes
- Read the GitHub API docs and suggest what needs changed
- GraphiQL or another REST API tool might help
- Try with a test account and see if it consistently happens

I prioritize my time based off the biggest issues, and when it’s one person hitting something I’d rather fix a bug or add a feature that everyone else is able to benefit from.

I made this project free and open source so it can be a community effort. It’s not mine or anyone else’s job to fix someone’s bug.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment] 2018-10-29 14:51
@Huddie @rnystrom hey, so I ended up adding another test account to githawk using the personal access tokens. I could be wrong, but from my memory, my initial account was not setup with a personal access token, but rather a normal login plus grant access portal. With the personal account token for account two, I granted full-access. The second account, I am able to fully action items without restriction that were failing every time with the primary account. 

1) am I incorrectly recalling how primary accounts were granted access?
2) is there a way to adjust primary account access or must I revoke and readd (would doing so incur any loss of data anywhere, especially githawk bookmarks? —speaking of which, I wish there was a way to back those up somewhere)
3) do my findings thus far change anything for this issue for either of you?

**Comment by Huddie** [comment] 2018-10-29 18:29
You should be able to check your access level. Pretty sure we have it in settings a link to your access 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment] 2018-10-29 19:17
Yeah @Huddie this was different. The access you refer to highlight 3 items. I enabled like 15 for the option under developer settings as I had to set it up to generate the token.

Was I accurate that the first account doesn’t need a token and was a portal signup?

**Comment by Huddie** [comment] 2018-10-29 21:01
Ya regular sign in I believe only has 3 access items. Private repos, access notifications, update user info. 

I’d suggest:
A) Try to figure out which repos/actions were having issues and see why it wouldn’t be covered in the 3 access. This can be confirmed with option B below. 
B) You could create ta bunch of personal tokens reducing what you allow to see where the issue lies... tedious 

Maybe @rnystrom has a better sense of where the issue is coming from but I’d suggest keeping up the diagnostic work and pinpoint the problem 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment] 2018-10-29 23:50
I’ve started doing this. I removed accesses and create a new set of permission for a token. But where would I insert this new token code in githawk? As far as a I see there is no way to remove an account or add new token info for an account (issue 1)

And I do not want to sign out of test account because that says it will sign me out of all accounts and lose my bookmarks (issue 2)

I do agree with this methodology otherwise to solve the overarching item (issue 3)

**Comment by ijm8710** [comment] 2018-10-30 00:46
Test

**Comment by ijm8710** [comment] 2018-10-30 00:48
Looks like it’s the public_repo permissions

**Comment by rnystrom** [comment] 2018-10-30 14:44
@ijm8710 thanks for this! Is there a scope were missing from the login flow? I feel like there’s something missing there but I thought we are requesting the broadest scopes possible...

https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/

Atm we request `user`, `repo`, and `notification`

https://github.com/GitHawkApp/GitHawk/blob/master/Classes/Login/LoginSplashViewController.swift

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment] 2018-10-30 15:06
public_repo is under repo. @ijm8710 what makes it seem like public_repo is the issue? Removing public_repo would def. result in an issue in-app but doesn’t mean it’s what’s causing the problem. 
Maybe try removing only the scopes we don’t request and see from those. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment] 2018-10-30 18:52
@Huddie @rnystrom  completely see where you guys are coming from and how the code lists user repo and notification. And how public_repo is a sub-asset of public. But in doing my diagnosis myself, that is exactly what I did. I created 10-15 different tokens adding and removing different permissions and confidently diagnosed that public_repo is the issue and that just having that permission solves the issue I see and removing it repro’s the issue identically.

I’m guessing perhaps the  line item code that that might need to be slightly tweaked. Perhaps the fact that it references private affects or. I’m not sure but what I am 99% sure about is public_repo permissions are currently not being granted.

Let me know if there’s anything else you need me to do on this ticket. I did mention a few items [here](https://github.com/GitHawkApp/GitHawk/issues/2165#issuecomment-434122134). Basically a couple things that bug-testing this causes me to notice about the app that could be optimized. Please let me know if you feel either of them are relevant, I can individually ticket either or both of them and hopefully my diagnosis here helps spur solving the main ticket on this. Thanks.

**Comment by rnystrom** [comment] 2018-10-31 13:28
I’m going to try to setup a script to repro this and plug in different scopes. 

The big bummer is that even if we solve this, people will have to logout/login to get the new permissions...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment] 2018-10-31 13:35
Are you saying that if you repro this, only existing users will be affected by having to re-login..and new users should be good going forward assuming the permissions can be tweaked?

This brings up one of the things I referenced in my last reply. I know you try to have as little server side items as possible for user safety, but is there any workaround to retain bookmarks with a log out?

I also asked if there was a way to remove an account without fully logging out and/or adjust permissions on a logged in account.Just things I came across when testing this.

**Comment by ijm8710** [comment] 2018-10-31 13:35
Are you saying that if you repro this, only existing users will be affected by having to re-login..and new users should be good going forward assuming the permissions can be tweaked?

This brings up one of the things I referenced in my last reply. I know you try to have as little server side items as possible for user safety, but is there any workaround to retain bookmarks with a log out?

I also asked if there was a way to remove an account without fully logging out and/or adjust permissions on a logged in account.Just things I came across when testing this.

**Comment by rnystrom** [comment] 2018-11-01 12:44
Ya exactly. New users would be fine.

Let’s keep the bookmarks discussion in another issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment] 2018-11-05 00:19
Gonna do some live debugging here...

---

Trying to send a `HEART` to [this comment on babel/babel](https://github.com/babel/babel/issues/8971#issue-377184758). I'm using this GraphQL:

```GraphQL
mutation {
  addReaction(input: {subjectId: "MDU6SXNzdWUzNzcxODQ3NTg=", content: HEART}) {
    subject {
      viewerCanReact
      id
    }
  }
}
```

Using a token from intercepted from the basic auth route ("Sign in with GitHub" button) yields this result:

```json
{
  "data": {
    "addReaction": null
  },
  "errors": [
    {
      "message": "Although you appear to have the correct authorization credentials,\nthe `babel` organization has enabled OAuth App access restrictions, meaning that data\naccess to third-parties is limited. For more information on these restrictions, including\nhow to whitelist this app, visit\nhttps://help.github.com/articles/restricting-access-to-your-organization-s-data/\n",
      "type": "FORBIDDEN",
      "path": [
        "addReaction"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

Using a Personal Access Token with `repo`, `user`, and `notification` scopes gives this:

```json
{
  "data": {
    "addReaction": {
      "subject": {
        "viewerCanReact": true,
        "id": "MDU6SXNzdWUzNzcxODQ3NTg="
      }
    }
  }
}
```

> Here's the setup in PAT config

<img width="590" alt="screen shot 2018-11-04 at 7 09 14 pm" src="https://user-images.githubusercontent.com/739696/47971973-36c50380-e065-11e8-8802-eb962c5466ae.png">

And confirmed in the .com UI:

<img width="404" alt="screen shot 2018-11-04 at 7 11 31 pm" src="https://user-images.githubusercontent.com/739696/47971995-7a1f7200-e065-11e8-9d94-cfe7c90029f6.png">

Now [this section](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#understanding-scopes-for-oauth-apps) in the "Understanding Scopes" docs has this:

<img width="674" alt="screen shot 2018-11-04 at 7 12 33 pm" src="https://user-images.githubusercontent.com/739696/47972007-9de2b800-e065-11e8-8cc2-3f361103e581.png">

So when I send a `curl` to `https://api.github.com/users/rnystromtest` to get scopes, using the PAT I get:

**X-OAuth-Scopes for PAT**:

```
notifications, repo, user
```

Then w/ the intercepted token:

**X-OAuth-Scopes for intercepted**:

```
notifications, repo, user
```

**Comment by rnystrom** [comment] 2018-11-05 00:28
Now let's try using the [V3 API for Reactions](https://developer.github.com/v3/reactions/)...

We can use the [create Reaction for an Issue API](https://developer.github.com/v3/reactions/#create-reaction-for-an-issue).

**URL**
```
POST: https://api.github.com/repos/babel/babel/issues/8971/reactions
```

**JSON Body**
```json
{
  "content": "heart"
}
```

**Header**
```
Accept: application/vnd.github.squirrel-girl-preview+json
```

Using the PAT:

```json
{
	"id": 31889413,
	"node_id": "MDg6UmVhY3Rpb24zMTg4OTQxMw==",
	"user": {
		"login": "rnystromtest",
		"id": 28745486,
		"node_id": "MDQ6VXNlcjI4NzQ1NDg2",
		"avatar_url": "https://avatars1.githubusercontent.com/u/28745486?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/rnystromtest",
		"html_url": "https://github.com/rnystromtest",
		"followers_url": "https://api.github.com/users/rnystromtest/followers",
		"following_url": "https://api.github.com/users/rnystromtest/following{/other_user}",
		"gists_url": "https://api.github.com/users/rnystromtest/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/rnystromtest/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/rnystromtest/subscriptions",
		"organizations_url": "https://api.github.com/users/rnystromtest/orgs",
		"repos_url": "https://api.github.com/users/rnystromtest/repos",
		"events_url": "https://api.github.com/users/rnystromtest/events{/privacy}",
		"received_events_url": "https://api.github.com/users/rnystromtest/received_events",
		"type": "User",
		"site_admin": false
	},
	"content": "heart",
	"created_at": "2018-11-05T00:26:15Z"
}
```

> Wo just noticed the `node_id`!! Need to follow up if that's available in notifications.

And we got the reaction 👌 

<img width="446" alt="screen shot 2018-11-04 at 7 26 42 pm" src="https://user-images.githubusercontent.com/739696/47972173-ac31d380-e067-11e8-8323-4632984218b9.png">

Now what about the normal token?

```json
{
	"id": 31889458,
	"node_id": "MDg6UmVhY3Rpb24zMTg4OTQ1OA==",
	"user": {
		"login": "rnystrom",
		"id": 739696,
		"node_id": "MDQ6VXNlcjczOTY5Ng==",
		"avatar_url": "https://avatars2.githubusercontent.com/u/739696?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/rnystrom",
		"html_url": "https://github.com/rnystrom",
		"followers_url": "https://api.github.com/users/rnystrom/followers",
		"following_url": "https://api.github.com/users/rnystrom/following{/other_user}",
		"gists_url": "https://api.github.com/users/rnystrom/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/rnystrom/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/rnystrom/subscriptions",
		"organizations_url": "https://api.github.com/users/rnystrom/orgs",
		"repos_url": "https://api.github.com/users/rnystrom/repos",
		"events_url": "https://api.github.com/users/rnystrom/events{/privacy}",
		"received_events_url": "https://api.github.com/users/rnystrom/received_events",
		"type": "User",
		"site_admin": false
	},
	"content": "heart",
	"created_at": "2018-11-05T00:28:21Z"
}
```

Success 😕 

<img width="417" alt="screen shot 2018-11-04 at 7 28 36 pm" src="https://user-images.githubusercontent.com/739696/47972193-dbe0db80-e067-11e8-903f-2ffe407eb802.png">

**Comment by ijm8710** [comment] 2018-11-05 00:35
I feel it’s because graphql does not grant  public_repo access

**Comment by rnystrom** [comment] 2018-11-05 00:36
@ijm8710 is there something I'm missing? `public_repo` is a **subset** of `repo` access, so its all included.

<img width="475" alt="screen shot 2018-11-04 at 7 35 38 pm" src="https://user-images.githubusercontent.com/739696/47972318-ebacef80-e068-11e8-8093-d9fef88c6b03.png">

**Comment by ijm8710** [comment] 2018-11-05 00:44
Perhaps what I tested means absolutely nothing, but I noticed that just having public_repo made all these fails nonexistent and vice versus. Perhaps full repo access is omitting this subpermission. I’m prob focused on the wrong thing but it just seemed a huge coincidence that that access related 1:1 with the issue itself

**Comment by rnystrom** [comment] 2018-11-05 00:48
Let me try manually changing the auth scope in GitHawk, logging in, and using that token.

[Btw filed this on the GitHub API forums](https://github.community/t5/GitHub-API-Development-and/Getting-quot-OAuth-App-access-restrictions-quot-for-GraphQL/m-p/14409#M220).

**Comment by ijm8710** [comment] 2018-11-05 00:49
^yeah this is what I did in my testing :) happy for you to mirror

**Comment by ijm8710** [comment] 2018-11-05 00:50
Not sure your link works in your link

**Comment by rnystrom** [comment] 2018-11-05 00:55
Confirmed that using using `public_repo` and `public_repo+repo` in the [loginUrl](https://github.com/GitHawkApp/GitHawk/blob/master/Classes/Login/LoginSplashViewController.swift#L14) for scopes doesn't change anything. 

@ijm8710 did you only get it working just by using a PAT? Not normal OAuth?

**Comment by ijm8710** [comment] 2018-11-05 00:55
Correct only PAT

**Comment by rnystrom** [comment] 2018-11-05 00:56
Ok, ya that was known for a while as the problem. It's normal auth that is the issue.

**Comment by ijm8710** [comment] 2018-11-05 00:57
Sorry ;) and yeah you might have to reset your link in the troublehsoot post

**Closed** 2018-12-29 20:54 UTC
Labels: github-bug, question
