### ISSUE TITLE
Never ending loader

### ISSUE THREAD

**Issue by kdawgwilk** [GitHawkApp/GitHawk#2233] opened 2018-10-06 03:45 UTC
On the current beta I keep getting this never ending spinner after app launch

![GitHawk Upload by kdawgwilk](https://i.imgur.com/hDvkrq7.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.23.0 (1538244553)
Device: iPhone X (iOS 12.0)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment] 2018-10-06 07:43
Dupe of #2230

**Closed by BasThomas** 2018-10-06 07:43 UTC
