### ISSUE TITLE
Cannot attach image to bug report

### ISSUE THREAD

**Issue by aviflax** [GitHawkApp/GitHawk#2843] opened 2019-11-06 02:33 UTC
I tap the little upload icon, choose an image, then I’m taken to a view showing only the image and a text input for a caption. There’s no way to exit this view. There’s no back button, no submit or cancel button, no buttons at all!

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone X (iOS 13.2)
TestFlight: false
</pre>
</details>

**Comment by aviflax** [comment] 2019-11-06 02:34
I uploaded this via the GitHub Web UI:

![9513BB33-AA77-422A-B323-3824DE2FE368](https://user-images.githubusercontent.com/141844/68263438-06b39600-0014-11ea-8eeb-d3a9ff235ddc.png)

**Comment by aviflax** [comment] 2019-11-06 02:35
Sorry for the screenshot-ception. Didn’t mean to do that.

**Comment by matteinn** [comment] 2019-11-09 22:57
Dupe of #2842

**Closed** 2019-11-09 22:57 UTC
