### ISSUE TITLE
Tiny labels on tab bar

### ISSUE THREAD

**Issue by gingerbeardman** [GitHawkApp/GitHawk#2384] opened 2018-11-02 20:16 UTC
Text labels are tiny and kerning is very tight making them difficult to read. 

iOS 12.1
iPhone 6s

![GitHawk Upload by gingerbeardman](https://i.imgur.com/trorx4A.jpg)

I'm using standard text sizing on iOS. 

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.23.0 (1541158684)
Device: iPhone 6s (iOS 12.1)
TestFlight: true
</pre>
</details>

**Comment by gingerbeardman** [comment] 2018-11-02 20:19
Compare to eBay app

![GitHawk Upload by gingerbeardman](https://i.imgur.com/Bl6V588.jpg)

**Comment by rnystrom** [comment] 2018-11-02 21:01
Wo this is really weird. I can repro this only by:

- Go to inbox
- Open this issue
- **Swipe** back

Has to be swipe. Tapping the back button doesn’t do it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment] 2018-11-02 21:02
Willing to bet this is an iOS 12.1 issue. Have literally never noticed til I updated this morning.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment] 2018-11-02 21:31
Yup not just us

https://twitter.com/_ryannystrom/status/1058470836229804032?s=21

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kimdv** [comment] 2018-11-10 23:56
![Icon by kimdv](https://i.imgur.com/krKXUeI.jpg)

Icons are also behaving strange 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment] 2018-11-11 01:34
TabHawk 😄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment] 2019-02-20 21:39
This is fixed in the new iOS 12 version, right? Not sure about the swiping from @kimdv though...

**Comment by BasThomas** [comment] 2019-02-20 21:39
(just tried to reproduce, seems to be fixed!)

**Closed by BasThomas** 2019-02-20 21:39 UTC
Labels: :bug: bug
