### ISSUE TITLE
Opening PR causes crash

### ISSUE THREAD

**Issue by bobheadxi** [GitHawkApp/GitHawk#1722] opened 2018-04-11 15:22 UTC
Opening [this PR](https://github.com/ubclaunchpad/inertia/pull/139) causes a crash

iPhone SE, iOS 11.4

Edit: looks like I can’t open any PRs :(

**Comment by jdisho** [comment] 2018-04-11 15:40
Duplicate of #1719 and is already fixed by this PR #1720. @bobheadxi 
I tried it with the latest version of `master` branch and it works.
Try it with that one 😊

**Closed by jdisho** 2018-04-11 15:40 UTC
