### ISSUE TITLE
Accessibility Bug Bash

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#934] opened 2017-11-13 15:22 UTC
I want to challenge all of our collaborators to the do the following:

- [Enable VoiceOver](https://support.apple.com/en-us/HT204390) on your device and open GitHawk.app
- Close your eyes (or triple tap with three fingers) and complete each of the challenges below
- Take notes on your experience (comments, difficulties, blockers)

## 1. Posting a new issue

- Find the "githawk-playground" repo
- Create a new issue w/ a title and brief description
- Go to your new issue and read it
- Pretend there is a typo and edit the comment

## 2. Login

- Make sure you're logged out of the app
- Login w/ your username + password
- _Bonus points for using a Personal Access Token_

## 3. Mark a notification read

- Make a notification read
  - I don't care how you accomplish this (enabling setting, swipe control) I just want to see how intuitive/easy it is

## 4. Manage an issue

- Find #933
- Update its labels
- Read who the issue is assigned to

---

cc @BasThomas @Sherlouk @heshamsalman @weyert @rizwankce would love your feedback!

**Comment by Sherlouk** [comment] 2017-11-13 19:06
"Ghit Hawk" 😂 

https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/plist/info/CFBundleSpokenName

^ Override the name VoiceOver says, maybe put a space in there to handle it a bit better
Also GitHub referenced throughout the app is entertaining, VO users probably used to it though.

Mentioned it on the accessibility card and while I 100% agree with Bas that it requires more maintenance, I find it takes too long for VO to tell me what the issue is? (It's basically the last thing it tells me!)

I found it particularly difficult to edit labels, I couldn't get my cursor to select the cell only the label within the cell but selecting that doesn't select the label if you get what I mean?

Can't actually read any comments, feel like this is the biggest issue by far.

Events such as adding labels are broken up into multiple objects. This should be one VO item which reads it all out. Allowing the user to just swipe through each of the events and have it read out.

I couldn't get it to read out assigned events

Could send a message fairly easily tbh, but I didn't really know when I had sent the comment? Obviously the UI all updates and you scroll to the comment. We should be posting a VO screen updated notification and probably say something like "Comment Successfully Posted" or something?

Preview is pointless, can't do anything with it

Markdown actions don't have accessibility labels "Button" "Button" "Button" "Button"!

**Comment by rnystrom** [comment] 2017-11-13 20:06
Omg, the name 🤭

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by heshamsalman** [comment] 2017-11-13 20:08
Blindfold-test is always a good idea before release :+1:

**Comment by BasThomas** [comment] 2017-11-18 18:23
## 1.

Nooo, I didn't change my typing settings with VoiceOver on my X yet, this typing sucks now :(

New issue: body is just "text field", don't know what kind of text field

New issue: submit should be magic tap (also when editing)

New issue: "Open" was confusing -> was the state of the issue after I looked, should be more descriptive

New issue: Nothing says "Hello" is the title, "basthomas" is the user. As @Sherlouk mentioned, the comment itself isn't accessible at all!

More options should be more descriptive -> more options for issue / more options for comment or similar


## 2.

"Welcome to GitHawk, an open source app for open source projects" could be / should be grouped

Couldn't login; getting a 404 it seems 😮

OK so SafariVC in VoiceOver mode might not have the cancel button at the top left in its hierarchy... ugh. That might be a VoiceOver bug.

Logged in with a PAT afterwards, worked fine!

## 3.

Used the mark as read option, since the swipeable action is not accessible as far as I know? Think I created a comment for it in the Accessibility ticket.

Afterwards - since I had never used this before - the issue was still there, and VoiceOver didn't indicate is was marked as read.

## 4.

Tried doing this via the repo, but all cells there are just "button"s 😱 Went to the issue without screen curtain.

The Manage button should have a hint explaining it a bit more; wouldn't hurt at least.

The buttons within the Manage aren't buttons and also just say "Labels" or "Milestone". Should be something like "Edit Labels" or "Edit Milestone" or similar?

Label cells are all "dimmed" and do not tell if they are enabled or not - it should select the cell instead of the button.

"Assignees" is not marked as a button.

Also didn't understand the "Load More" button? Thought it would load more assignees maybe? Even without screen curtain / as a normal user it is a weird button that I do not understand.

**Comment by rnystrom** [comment] 2017-11-20 14:11
If you all can help task out any of this that'd be much appreciated! I configured milestone 2.0.0 for larger AX updates (nothing preventing us from fixing them now tho).

**Comment by BasThomas** [comment] 2018-01-14 16:28
Assigned myself to remind me to split this into separate tickets.

**Closed** 2018-08-11 19:15 UTC
Labels: bug, high
