### ISSUE TITLE
Re-arrange Bookmarks order

### ISSUE THREAD

**Issue by iDjay** [GitHawkApp/GitHawk#2664] opened 2019-03-06 16:12 UTC
Would be great if we can re-arrange the bookmarks order :)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone XS (iOS 12.1.4)
TestFlight: false
</pre>
</details>

**Comment by iDjay** [comment] 2019-03-06 17:08
And maybe a single swipe option to remove the items

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment] 2019-03-08 21:38
Dupe of #2376 #1886 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2019-03-08 21:39 UTC
Labels: Dupe, feature-request
