### ISSUE TITLE
Close issue action available on issues where I’m not allowed to close them

### ISSUE THREAD

**Issue by viktorgardart** [GitHawkApp/GitHawk#2042] opened 2018-08-05 20:12 UTC
![GitHawk Upload by viktorgardart](https://i.imgur.com/jo7rz5R.jpg)

Caused by #2033 I believe.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1533487686)
Device: iPhone X (iOS 11.4.1)
TestFlight: true
</pre>
</details>

**Comment by viktorgardart** [comment] 2018-08-05 20:14
Same with reopen if issue is already closed. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment] 2018-08-05 20:38
I think this is a dupe of #1992

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed by rnystrom** 2018-08-05 20:38 UTC
