### ISSUE TITLE
API Status web page will be deprecated

### ISSUE THREAD

**Issue by ChengLuffy** [GitHawkApp/GitHawk#2597] opened 2019-01-07 12:15 UTC
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone XS (iOS 12.1.2)
TestFlight: false
</pre>
</details>

**Comment by Sherlouk** [comment] 2019-01-07 12:16
Dupe of #2546 - fix in progress 😄

**Closed by Sherlouk** 2019-01-07 12:16 UTC
