### ISSUE TITLE
Wants a profile page

### ISSUE THREAD

**Issue by peterzililuo** [GitHawkApp/GitHawk#2488] opened 2018-11-26 11:31 UTC
I really wants a profile for myself, you know, kind of page shows my repositories, stars, and things about my self
But now GitHawk is mainly focused on the part of exploring GitHub, I think that it is really important to have a personal profile page

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by viktorgardart** [comment] 2018-11-26 11:37
Duplicate of: #317 #2113

**Closed** 2018-11-26 11:53 UTC
