### ISSUE TITLE
Can't view branches on iPhone?

### ISSUE THREAD

**Issue by thirtytwobits** [GitHawkApp/GitHawk#2028] opened 2018-08-03 16:21 UTC
Under the "code" tab for a repository there's no way to select a branch to browse.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.21.0 (1528145114)
Device: iPhone 7 Plus (iOS 11.4.1)
TestFlight: false
</pre>
</details>

**Comment by jdisho** [comment] 2018-08-03 21:48
Dupe of https://github.com/GitHawkApp/GitHawk/issues/372, https://github.com/GitHawkApp/GitHawk/issues/1796

**Closed by jdisho** 2018-08-03 21:48 UTC
Labels: question
