### ISSUE TITLE
Tab dark when on bookmarks page

### ISSUE THREAD

**Issue by Sherlouk** [GitHawkApp/GitHawk#1217] opened 2017-12-09 23:36 UTC
![GitHawk Upload by Sherlouk](https://i.imgur.com/9jQUuLT.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.16.0 (1512840803)
Device: iPhone 6s Plus (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment] 2017-12-10 01:49
Wat, this is weird. Doesn’t happen on my X. Persist after a restart?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment] 2017-12-10 10:50
On hard restart it does go, but soon comes back when you start navigating to repos etc from the bookmarks page

Rushed report, but the screenshot was taken on a repo issues page navigated from bookmarks

**Comment by rnystrom** [comment] 2017-12-10 15:54
Wonder if it’s an 11.2 regression? I’ll update stuff and check. If you get a SEV to manually debug, or can use FLEX to inspect the view hierarchy, that’d be handy.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment] 2017-12-10 16:00
@rnystrom If I bounce the overview tab horizontally then the background is a dark grey (so behind the overview VC, likely the TabBarVC background)

**Comment by rnystrom** [comment] 2018-08-11 19:14
Closing since this doesn't seem to be a thing, no other reports

**Closed by rnystrom** 2018-08-11 19:14 UTC
Labels: bug, high
