### ISSUE TITLE
[Proposal] Supporting GitLab

### ISSUE THREAD

**Issue by jdisho** [GitHawkApp/GitHawk#1650] opened 2018-03-14 19:11 UTC
What if, in a near future GitHawk supports also Gitlab? 

Thoughts? 💭

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment] 2018-03-14 19:16
This is a duplicate of #408

**Closed** 2018-03-14 19:20 UTC
Labels: no-api-yet, wishlist

**Comment by jdisho** [comment] 2018-03-14 19:21
Aah!!! 😄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
