### ISSUE TITLE
Overlapping content

### ISSUE THREAD

**Issue by gingerbeardman** [GitHawkApp/GitHawk#1391] opened 2018-01-13 09:52 UTC
Not sure how this happened. I was trying to like the comment and it didn't work, so I then tapped the content to expand it and the emoji thing stayed where it was. 

![Imgur](https://i.imgur.com/0efGxKz.png)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1515261323)
Device: iPhone 6s (iOS 11.2.2)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment] 2018-01-13 10:11
I know I definitely raised an issue for this in the past, but can't remember how I worded it and whether it was closed as a can't reproduce or left open for investigation 😬 

Are you able to reproduce this at all?

**Comment by Sherlouk** [comment] 2018-01-13 19:18
#1013 was the issue I raised, pretty much the same but didn't have the menu open (not sure if that changes anything)

@rnystrom Maybe worth another look since others have experienced now?

**Comment by rnystrom** [comment] 2018-01-13 21:30
Can’t do much without a repro atm. If you can use FLEX and dump the view hierarchy that’d give us a start for sure.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment] 2018-01-13 22:07
Yes I can reproduce, the first thing I tried: 

1. Open an issue with a collapsed comment
2. Tap the emoji button then quickly
3. Tap the comment above it to expand 

I've got a video of me doing it multiple times, but I can't upload it just yet. So here's another image. 

![GitHawk Upload by gingerbeardman](https://i.imgur.com/baguvv0.jpg)

**Comment by BasThomas** [comment] 2018-01-13 22:09
Can you dump the view hierarchy? You can open FLEX [by tapping with three fingers](https://github.com/rnystrom/GitHawk/issues/1339#issuecomment-356379395).

**Comment by gingerbeardman** [comment] 2018-01-13 22:23
Sure, i have opened Flex but what do I do next?

**Comment by Sherlouk** [comment] 2018-01-13 22:25
I too can reproduce it super easily using that exact comment shown above, but struggling with others - So that makes me think it's something to do with the content or the total size of the comment (it's a relatively large text only comment!)

![img_b925ee6eb28e-1](https://user-images.githubusercontent.com/15193942/34910609-a57320c0-f8b0-11e7-85f4-87d7a22deb4e.jpeg)

**Comment by gingerbeardman** [comment] 2018-01-13 22:27
Herems one from me 

![GitHawk Upload by gingerbeardman](https://i.imgur.com/hFApvrf.jpg)

**Comment by Sherlouk** [comment] 2018-01-13 22:30
Apologies for this, just wanting to see if a lot of basic text will cause this to happen!

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas erat ipsum, facilisis nec mauris ac, suscipit eleifend orci. Donec aliquam sagittis mollis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; 

Ut cursus neque nisl, eu pulvinar urna convallis ut. Fusce in mi nisl. Curabitur sit amet ullamcorper mi. Nulla blandit convallis nisi, ut finibus arcu egestas at. Donec finibus metus eget dui aliquet, quis efficitur risus viverra.

Quisque nec ultricies sem. Nullam sagittis ligula sed lectus pellentesque, sed sollicitudin urna feugiat. Suspendisse euismod sapien non neque porttitor, varius tincidunt felis lobortis. Morbi dictum malesuada nibh eu gravida. 

Sed volutpat, orci et venenatis convallis, ex justo tristique sapien, ac posuere sapien tellus eu nisi. Nunc dictum dictum rhoncus. Suspendisse potenti. Suspendisse vel nunc eleifend, hendrerit lacus non, laoreet enim. Sed condimentum ipsum ut lorem bibendum, sed commodo tellus commodo. Aenean in posuere neque.

Mauris non libero quis enim gravida cursus vel euismod nibh. Fusce semper turpis nisi, in efficitur orci venenatis eu. Vestibulum eu maximus risus. Nunc sollicitudin ligula feugiat risus cursus, quis vestibulum dolor blandit. Vestibulum nec interdum dui. Nulla a sapien et ipsum imperdiet ultrices. Vivamus aliquet dictum congue. 

Cras ac mi sed urna porta placerat eu non ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed nibh tincidunt, tristique mauris sed, suscipit neque.

Nunc dolor sem, fermentum non urna in, dignissim tempus dolor. Vestibulum eget turpis ipsum. Vivamus ipsum dolor, feugiat nec ultrices in, vulputate dapibus erat. Curabitur in molestie sem, id ultricies est. Phasellus ut maximus augue. Vivamus venenatis dui eu diam efficitur, vitae dignissim velit tincidunt. Sed sagittis tellus ex. 

Proin a arcu in nisl euismod sodales. Praesent ac fringilla enim. In feugiat tellus vitae pulvinar pellentesque. Quisque dignissim risus a laoreet tristique. Aenean varius pulvinar tortor, in dignissim lacus ornare at. Donec viverra nisi sed malesuada pretium. In luctus laoreet orci, non aliquet mauris mollis at.

Integer dictum ac enim in tristique. Maecenas et elementum enim, at auctor metus. In ut mollis ipsum. Quisque ac nisl at nisl hendrerit cursus. Sed placerat ante id interdum pellentesque. Nulla eget dictum est. Ut ultrices tellus in nunc pretium fermentum. Vestibulum tellus eros, tincidunt faucibus dui quis, semper interdum leo. Cras rhoncus suscipit lacus et iaculis. Vivamus leo neque, ullamcorper nec elit ac, dignissim euismod augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce lacus nunc, elementum sit amet lacus quis, dictum blandit elit.

**Comment by Sherlouk** [comment] 2018-01-13 22:36
Okay so a little bit of experiment and a whole load of editing the comment above, it looks like it's based on the extended height?

On my phone (6s plus) if I remove even one line from it then it doesn't happen 🤔

**Comment by Sherlouk** [comment] 2018-01-13 22:38
Okay a lot of experimenting and editing the previous comment, I think I've narrowed it down to if you extend the comment and it's new height exceeds out of the screen bounds (plus a buffer).

In the same way a table view cell loads in a little before it comes on screen, I suspect if the new height pushes the reaction cell out of that buffer, it doesn't know where to place it? and so doesn't do anything?

@rnystrom

**Comment by rnystrom** [comment] 2018-01-14 00:06
Everyone give the latest beta a try. Seems like it’s fixed?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment] 2018-01-14 09:35
Can still reproduce really easily following the same steps on the original comment

**Comment by gingerbeardman** [comment] 2018-01-14 10:35
Hmm, that'll teach me to test and close a bug at 1AM. Force quitting the app and I can now reproduce.

It could be my hazy memory of last night but when it worked I seem to remember the "fade" being a lot darker in colour than it is after relaunching the app?

**Comment by Sherlouk** [comment] 2018-01-14 13:14
So I _sorta_ fixed it by dropping an invalidate layout in here: https://github.com/rnystrom/GitHawk/blob/master/Classes/Issues/Comments/IssueCommentSectionController.swift#L137

`collectionContext?.invalidateLayout(for: self, completion: nil)`

It doesn't move the menu, but the actual cell does move
🤔

**Comment by rnystrom** [comment] 2018-01-14 16:47
Aha! I see now. Ok. I wonder if we just need to do something where if the reaction cell is the first responder, we don't uncollapse? I'll give it a try, brb.

**Comment by Sherlouk** [comment] 2018-01-15 20:29
Can still reproduce on latest TestFlight 😖 same steps! (Though the menu does close now? But reaction cell sticks)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment] 2018-01-15 21:59
I can no longer reproduce

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment] 2018-01-15 22:10
@gingerbeardman Even with the new steps in my previous comment? (Tapping the bubble then the reaction cell?)

I can reproduce quite easily

**Comment by gingerbeardman** [comment] 2018-01-15 22:16
Ah, OK, new steps.

Yes, I can reproduce. 

![GitHawk Upload by gingerbeardman](https://i.imgur.com/JvromrU.jpg)

**Comment by gingerbeardman** [comment] 2018-01-15 22:20
My steps are now: 

1. Open emoji bar
2. Tap an emoji
3. Tap comment to expand

**Comment by rnystrom** [comment] 2018-01-16 12:11
@Sherlouk @gingerbeardman im gonna let you guys dig and find a solution here. Seems pretty edge case and you have to try hard to repro, so not blocking 1.17.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment] 2018-01-16 12:13
@rnystrom Invalidating the layout as I listed above did seem to always force the reaction bar back down to where it should be with the menu being the issue. The menu is no longer an issue, so it should be a final solution -- Not sure if it has implications on performance or anything?

Your opinion?

Happy to leave this if you think it's super low pri, but I've experienced it a couple times without trying what so ever (mostly when there's an image near the fade boundary)

**Comment by gingerbeardman** [comment] 2018-01-16 12:21
I don't have to try hard at all to reproduce. First time every time with these steps: 

1. Open the emoji bar
2. Tap an emoji to add it to the comment
3. Tap the comment to expand

Here's a video: http://www.youtube.com/watch?v=JJvny6hs0f8

But I agree it shouldn't be a blocker, low priority.

**Comment by rnystrom** [comment] 2018-01-16 13:21
@Sherlouk ya if you wanna put up a PR invalidating there we can give that a shot

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment] 2018-03-21 22:40
Another one 
A
![GitHawk Upload by gingerbeardman](https://i.imgur.com/8AiYYSr.jpg)

**Closed** 2018-03-22 01:38 UTC
Labels: bug, low
