### ISSUE TITLE
Subscribe to issue/PR

### ISSUE THREAD

**Issue by lleger** [GitHawkApp/GitHawk#2511] opened 2018-12-01 17:59 UTC
Is it possible to subscribe to notifications for a specific issue or PR from GitHawk? This is not for the _repo_ but for issues individually. For clarity I’m talking about the following button on GitHub’s website. 

![GitHawk Upload by lleger](https://i.imgur.com/L33JhCZ.jpg)

**Comment by lleger** [comment] 2018-12-01 18:00
My current workaround is to hit the share button -> open in Safari -> scroll down to pictured button. Which is fine but it’d be great to have it build into the UI!

**Comment by rnystrom** [comment] 2018-12-01 18:07
WIP with #2482 and dupe of #2149 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed by rnystrom** 2018-12-01 18:07 UTC

**Comment by lleger** [comment] 2018-12-01 19:02
Oops, I had found that PR when I searched but for some reason it didn’t register as the same in my head. On second read it does. 😅 Glad there’s a PR. Thanks!
