### ISSUE TITLE
Missing border on "no conflicts" panel

### ISSUE THREAD

**Issue by gingerbeardman** [GitHawkApp/GitHawk#2216] opened 2018-10-01 07:41 UTC
Witness: 

![GitHawk Upload by gingerbeardman](https://i.imgur.com/soCB4S0.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.23.0 (1538244553)
Device: iPhone 6s (iOS 12.0)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment] 2018-10-01 08:03
Dupe of this by chance? https://github.com/GitHawkApp/GitHawk/issues/2199

May have already been fixed but not deployed

**Closed** 2018-10-02 07:35 UTC
