### ISSUE TITLE
Warnings in console

### ISSUE THREAD

**Issue by jdisho** [GitHawkApp/GitHawk#1663] opened 2018-03-18 23:34 UTC
It happens when IssueViewController is open (`master` branch). 😕 @rnystrom 

<img width="1131" alt="screen shot 2018-03-18 at 20 26 58" src="https://user-images.githubusercontent.com/8223362/37572546-0b26d55e-2b0d-11e8-8850-3cd78a60baf4.png">

**Comment by SD10** [comment] 2018-03-18 23:45
SD10 bot has detected this is a duplicate of #1225 😝

**Comment by jdisho** [comment] 2018-03-18 23:49
It didn‘t happened a couple of hours ago... @SD10 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment] 2018-03-18 23:52
Ok, no problem @jdisho. I haven't been following everything that has been going on with GitHawk development lately. Maybe this was solved and we forgot to close #1225

**Comment by BasThomas** [comment] 2018-03-19 06:56
I don’t think that this has been fixed yet, and it should be a duplicate of #1225.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed by BasThomas** 2018-03-19 06:57 UTC
