### ISSUE TITLE
status.github.com is deprecated

### ISSUE THREAD

**Issue by n3oney** [GitHawkApp/GitHawk#2576] opened 2019-01-01 20:04 UTC
Status.github.com is deprecated, you should use githubstatus.com now ;)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.25.0 (1542806489)
Device: iPhone 6s (iOS 12.1.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment] 2019-01-01 20:06
Dupe of #2546, but thanks for pointing it out!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed by BasThomas** 2019-01-01 20:06 UTC
