### ISSUE TITLE
Can't delete branch after merge

### ISSUE THREAD

**Issue by genebean** [GitHawkApp/GitHawk#2138] opened 2018-08-22 19:12 UTC
It's critical in some of the repos I work in to be able to delete the branch right after merging... can this option be added in?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1534395229)
Device: iPhone 7 Plus (iOS 11.4.1)
TestFlight: false
</pre>
</details>

**Comment by jdisho** [comment] 2018-08-22 19:16
Dupe of #1542  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed by jdisho** 2018-08-22 19:16 UTC
